### ISSUE TITLE
App VPlan sollte auch "leere" Tage anzeigen

### ISSUE THREAD

**Issue by kagOT** [kagonlineteam/KAG-APP#122]
<p>Wollte mir gerade den Vertretungsplan für heute anschauen. Mir wird aber in der App und auch auf <a href="http://VPlan.kag-langenfeld.de">VPlan.kag-langenfeld.de</a> nur der 11.6 angezeigt.<br>
Ändern des Datums ist nicht möglich. <br>
Ort des Problems ist mein Androidhandy</p><br><p>Teste das gleich nochmal Mal iPad</p><br><p>OK, das scheint nur eine aus meiner Sicht unglückliche Darstellung zu sein.</p><br><p>Wenn ich den Filter lösche, dann sehe ich auch den Tag heute</p><br><p>Sobald ich filtere wird mir nur noch der Freitag angezeigt, weil ich heute keine Vertretung habe. Ein kleiner Hinweis "Sie haben heute keine Vertretung" unter dem Datum 10.06 hätte mich weniger verwirrt....</p><br><p>Das wäre eine sinnvolle Ergänzung!</p><br><p>Stimmt hatte ich schonmal gehört (von Schülern)</p><br>

**Comment by strifel** [comment]
75b7155c2b5dc73637fa8b7bfad936a684e7b558 implemented this
