### ISSUE TITLE
App startet nicht mehr

### ISSUE THREAD

**Issue by Nils2006** [kagonlineteam/KAG-APP#131]
### Was funktioniert nicht?
Die App auf dem Schulipad will nicht mehr aus dem Startscreen raus.

### Schritte um den Fehler zu reproduzieren
Bei der App anmelden und diese dann mehrmals Neustarten

**Comment by themathman2** [comment]
Kann ich auf dem Lehrer-Schulipad nicht reproduzieren. Bei mir läuft die App normal.

**Comment by strifel** [comment]
Hatte ich doch gestern auch kurz, oder?

**Comment by strifel** [comment]
Ich kann das aber gerade nicht reproduzieren am Handy

**Comment by Nils2006** [comment]
Bei mir funktioniert es auch wieder

**Comment by strifel** [comment]
Das einzige was ich mir vorstellen kann ist, dass das WLAN verbugt war und die Request an /users/username nicht geklappt hat, aber auch nicht abgebrochen wurde

**Comment by Phantom061** [comment]
Konnte ich reproduzieren nachdem ich die Nachricht geöffnet habe

**Comment by Phantom061** [comment]
Also die das neue Stundenpläne da sind

**Comment by themathman2** [comment]
hm... das ist spannend und evt. ein Ansatzpunkt

**Comment by strifel** [comment]
Gerade mehrfach ausprobiert. Kein Problem

**Comment by Phantom061** [comment]
Habe gerade eventuell einen Hinweis bekommen: Wenn kurz die Internetverbindung beim starten der App abbricht, bleibt man im ladescreen. Könnte in der Schule ja ab und zunpassieren :)

**Comment by strifel** [comment]
Kann das gerade auch mit ganz deaktiviertem Internet reproduzieren.
Obwohl das die App ohne Internet nicht startet finde ich ja noch vetretbar. (Auch wenn sie dann nicht nur im Startscreen bleiben sollte)
Ich schaue mal ob mir da was intelligentes einfällt

**Comment by strifel** [comment]
fddb19d5d39d25062446cf0c2375fc02aa66e604 müsste das beheben
