### ISSUE TITLE
Timer Animation entfernen

### ISSUE THREAD

**Issue by Phantom061** [kagonlineteam/KAG-APP#165]
### Was funktioniert nicht?

Die Timer Animation unter Linux

### Wie sollte es eigentlich funktionieren?

Nichts sollte kaputt gehen wegen dieser Animation

### Schritte um den Fehler zu reproduzieren
1. Linux installieren
2. App im Web ausprobieren

### Erste Lösungsvorschläge

Animation entfernen

**Comment by strifel** [comment]
> Sie soll einfach abgespielt werden

Ich dachte entfernt
