### ISSUE TITLE
Feature-Krankmeldungsservice

### ISSUE THREAD

**Issue by themathman2** [kagonlineteam/KAG-APP#183]
### Für wen ist das Feature und warum?

Für alle Eltern, die kranke Kinder haben und schnell mit dem Handy ne Krankmeldung rausschicken wollen.

### Use-Case: Wie kann das Feature verwendet werden?

Kinder krankmelden

### Implementations Ideen _(falls es welche gibt)_

Icon auf die Homeseite der App. Klick öffnet eine Unterseite, die das Eingabeformular enthält. Drücken des Absendenbuttons schließt das Eingabeformular und führt zurck auf die Landingpage.

**Comment by strifel** [comment]
Wir haben keine Home Seite in der mobilen Webseite.
Aber wir können einfach unten einen Tab dafür oder einen Tab Eltern hinzufügen

**Comment by themathman2** [comment]
Stimmt, habe ich auch gerade gesehen. Ein neuer Tab dafür, ist vielleicht nicht verkehrt. Überlege, ob man dort auch die Kontaktseite hinterlegt.

Nach dem Login könnte man die Verklickung zur Krankmeldung ja unter die Shortcut packen
